FROM openjdk:8-jre-alpine

# Proxy para wget
ENV HTTP_PROXY http://172.29.66.25:14100
ENV HTTPS_PROXY http://172.29.66.25:14100
ENV http_proxy http://172.29.66.25:14100
ENV https_proxy http://172.29.66.25:14100

RUN mkdir -p /opt && wget -q http://nilhcem.github.com/FakeSMTP/downloads/fakeSMTP-latest.zip && unzip fakeSMTP-latest.zip -d /opt && rm fakeSMTP-latest.zip
RUN mv /opt/fakeSMTP*.jar /opt/fakeSMTP.jar
EXPOSE 25
VOLUME ["/var/mail"]
CMD java -jar /opt/fakeSMTP.jar --start-server --background --output-dir /var/mail --port 25
