version: '2'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=somepassword
      - POSTGRES_HOST_AUTH_METHOD=trust
  django:
    build:
      context: .
      dockerfile: Dockerfile-nadine
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    environment:
      - POSTGRES_PASSWORD=somepassword
