version: '2.2'
services:
  fakesmtp:
    build:
      context: .
      dockerfile: Dockerfile-fakesmtp
    ports:
      - "1025:25"  
    volumes:
      - ./email:/var/mail
    image: gbottaro/nadine-fakesmtp:1.0.1
  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=somepassword
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: gbottaro/nadine-postgresql:1.0.1
  django:
    build:
      context: .
      dockerfile: Dockerfile-nadine
    ports:
      - "8000:8000"
    depends_on:
      - db
      - fakesmtp
    links:
      - db
      - fakesmtp
    environment:
      - POSTGRES_PASSWORD=somepassword
    image: gbottaro/nadine-django:1.0.3
